#! /bin/sh
# $Id: sys-xinitrc-fink.in,v 1.5 2008/02/18 06:41:09 okayama Exp $

# This script works even after the Fink "xinitrc" package is removed.
# Don't worry.

if test -r "/sw/etc/xinitrc-override"; then
    # If system administrator dislike xinitrc.d framework, create this file
    . "/sw/etc/xinitrc-override"
elif test -r "/sw/bin/xinitrc.sh"; then
    . "/sw/bin/xinitrc.sh"
else
    # Xterm and a window manager may be used for trouble shooting.
    # Run these programs carefully.

    userresources=$HOME/.Xresources
    usermodmap=$HOME/.Xmodmap
    sysresources=/usr/X11R6/lib/X11/xinit/.Xresources
    sysmodmap=/usr/X11R6/lib/X11/xinit/.Xmodmap
    x_bindir=/usr/X11R6/bin

    # merge in defaults and keymaps

    if test -f $sysresources; then
	xrdb -merge $sysresources
    fi

    if test -f $sysmodmap; then
	xmodmap $sysmodmap
    fi

    if test -f $userresources; then
	xrdb -merge $userresources
    fi

    if test -f $usermodmap; then
	xmodmap $usermodmap
    fi

    # start some nice programs

# Panther or Tiger only. On Leopard, use app_to_run in org.x.X11.plist instead.
case "`/usr/bin/uname -r`" in
7*|8*)
    if test -x "$x_bindir/xterm"; then
	termcmd="$x_bindir/xterm"
    else
	termcmd="xterm"
    fi
    $termcmd &
    ;;
esac

    # start the window manager

    if type quartz-wm >/dev/null 2>&1; then
	sessionmgr="`which quartz-wm`"
    elif test -x "$x_bindir/twm"; then
	sessionmgr="$x_bindir/twm"
    else
	sessionmgr="twm"
    fi
    exec $sessionmgr
fi
