;;; Automatically generated by `recentf' on Mon Apr 25 08:21:08 2011.

(setq recentf-list
      '(
        "/Users/burnett/.ido.last"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/appearance.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/keyboard-scrolling.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/initialize.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/keyboard-bindings.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/Preferences.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/customizations.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/clipboard.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/personal.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/file-finder.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/bubble-buffer.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/setup-abbrev-mode.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/auto-save.el"
        "/Users/burnett/tmp/.emacs"
        "/Users/burnett/.abbreviations.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/useful-functions.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/navigation.el"
        "/Users/burnett/Library/Preferences/Aquamacs Emacs/plugins/setup-iswitch-mode.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
